package com.example.Selenium;// Generated by Selenium IDE
import com.example.Selenium.Utils.Pauser;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Monitor20Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\ChromeDriver\\chromedriver.exe");
    ChromeOptions chromeOptions = new ChromeOptions();
    chromeOptions.addArguments("--incognito");
    driver = new ChromeDriver(chromeOptions);
  }
  @After
  public void tearDown() {
    driver.manage().deleteAllCookies();
    driver.quit();
  }
  @Test
  public void monitor20() {
    driver.get("https://portal.efd.lra.gov.lr/app");
    Pauser.pause(10);
    driver.manage().window().maximize();
    Pauser.pause(5);
    driver.findElement(By.cssSelector(".usernameField")).sendKeys("admin");
    Pauser.pause();
    driver.findElement(By.name("passwordField")).sendKeys("95u*3TW]BF+~");
    Pauser.pause();
    driver.findElement(By.cssSelector(".c-login-panel")).click();
    Pauser.pause();
    driver.findElement(By.cssSelector(".v-button")).click();
    Pauser.pause(10);
    driver.findElement(By.xpath("//*[@id=\"app-96801\"]/div/div[2]/div/div/div/div/div[1]/div/div/div[3]/div/div[2]/span/span[2]")).click();
    Pauser.pause(10);
    driver.findElement(By.xpath("//*[@id=\"app-96801\"]/div/div[2]/div/div/div/div/div[1]/div/div/div[3]/div/div[3]/div[1]/span/span")).click();
    Pauser.pause(20);
    driver.close();
  }
}
