package com.example.Selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SbmTmsModuleCheckerTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sbmTmsModuleChecker() {
    driver.get("https://41.215.130.247:444/#/login");
    driver.manage().window().setSize(new Dimension(1346, 708));
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("developer@tracom.co.ke");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("Data2020.");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.id("no-paste")).click();
    driver.findElement(By.id("no-paste")).sendKeys("655477");
    driver.findElement(By.cssSelector(".btn:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn:nth-child(1)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".tms")).click();
    {
      WebElement element = driver.findElement(By.linkText("Reports"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".panel:nth-child(2) .panel-heading .fa")).click();
    driver.findElement(By.cssSelector("#system_setup .dropdown:nth-child(1) > #parent-link > .fa-caret-right")).click();
    driver.findElement(By.cssSelector("#system_setup .dropdown:nth-child(1) > #parent-link > .fa-caret-right")).click();
    driver.findElement(By.linkText("Manufacturers")).click();
    driver.findElement(By.linkText("Approve Manufacturer")).click();
    driver.findElement(By.cssSelector(".even:nth-child(2) > .select-checkbox")).click();
    driver.findElement(By.cssSelector(".btn-info")).click();
    driver.findElement(By.id("mat-input-0")).click();
    driver.findElement(By.id("mat-input-0")).sendKeys("Approve Sele");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.linkText("Device Types")).click();
    driver.findElement(By.linkText("Approve Device Type")).click();
    driver.findElement(By.cssSelector(".even > .select-checkbox")).click();
    driver.findElement(By.cssSelector(".btn-info")).click();
    driver.findElement(By.id("mat-input-1")).click();
    driver.findElement(By.id("mat-input-1")).sendKeys("Approve device");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.linkText("Devices Models")).click();
    driver.findElement(By.linkText("Approve Model")).click();
    driver.findElement(By.cssSelector(".even > .select-checkbox")).click();
    driver.findElement(By.cssSelector(".btn-info")).click();
    driver.findElement(By.id("mat-input-2")).click();
    driver.findElement(By.id("mat-input-2")).sendKeys("Approve model");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.linkText("Business Units")).click();
    driver.findElement(By.linkText("Approve Business Units")).click();
    driver.findElement(By.cssSelector(".odd > .select-checkbox")).click();
    driver.findElement(By.cssSelector(".btn-info")).click();
    driver.findElement(By.id("mat-input-3")).click();
    driver.findElement(By.id("mat-input-3")).sendKeys("Approve business");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.linkText("Currency")).click();
    driver.findElement(By.linkText("Approve Currency")).click();
    driver.findElement(By.cssSelector(".odd:nth-child(3) > .select-checkbox")).click();
    driver.findElement(By.cssSelector(".odd:nth-child(1) > .select-checkbox")).click();
    driver.findElement(By.cssSelector(".btn-info")).click();
    driver.findElement(By.id("mat-input-6")).click();
    driver.findElement(By.id("mat-input-6")).sendKeys("Approve currency");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".dropdown:nth-child(2) > #parent-link > .fa-caret-right")).click();
    driver.findElement(By.cssSelector(".dropdown:nth-child(2) > #parent-link > .fa-caret-right")).click();
    driver.findElement(By.cssSelector(".dropdown:nth-child(2) > .ng-star-inserted > .ng-star-inserted:nth-child(1) > .ng-star-inserted")).click();
    driver.findElement(By.linkText("Password Complexity")).click();
    driver.findElement(By.linkText("Approve System Configuration")).click();
    js.executeScript("window.scrollTo(0,0)");
  }
}
