package com.example.Selenium;// Generated by Selenium IDE
import com.example.Selenium.Utils.Pauser;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import java.net.MalformedURLException;

public class SbmTmsModuleTest {
  private WebDriver driver;

  public SbmTmsModuleTest(WebDriver driver) {
    this.driver = driver;
  }

  @Before
  public void setUp() throws MalformedURLException {
    LoginUfsTest loginUfsTest = new LoginUfsTest(driver);
    loginUfsTest.setUp();
  }

  @After
  public void tearDown() {
    LoginUfsTest loginUfsTest = new LoginUfsTest(driver);
    loginUfsTest.tearDown();
  }
  @Test
  public void sbmTmsModule() throws InterruptedException {
    LoginUfsTest loginUfsTest = new LoginUfsTest(driver);
    loginUfsTest.loginUfs();
    Pauser.pause(10);
    driver.findElement(By.cssSelector(".tms > .mat-card-image")).click();
    Pauser.pause(10);
    driver.findElement(By.cssSelector(".panel:nth-child(2) .text-white")).click();
    Pauser.pause();
    driver.findElement(By.cssSelector("#system_setup .dropdown:nth-child(1) .fa-plus")).click();
    Pauser.pause();
    driver.findElement(By.cssSelector("#system_setup .dropdown:nth-child(1) .fa-plus")).click();
    Pauser.pause();
    driver.findElement(By.linkText("Manufacturers")).click();
    Pauser.pause();
    driver.findElement(By.linkText("Add Manufacturer")).click();
    driver.findElement(By.id("make")).click();
    driver.findElement(By.id("make")).sendKeys("Selenium");
    Pauser.pause();
    driver.findElement(By.id("vendorName")).click();
    Pauser.pause();
    driver.findElement(By.id("vendorName")).sendKeys("Selenium");
    Pauser.pause();
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("description")).sendKeys("Testing");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".buttons-pdf > span")).click();
    driver.findElement(By.cssSelector(".even:nth-child(6) > .select-checkbox")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.id("mat-input-0")).click();
    driver.findElement(By.id("mat-input-0")).sendKeys("Delete test");
    driver.findElement(By.cssSelector(".mat-button-wrapper > .text-white")).click();
    driver.findElement(By.linkText("Device Types")).click();
    driver.findElement(By.linkText("Add Device Type")).click();
    driver.findElement(By.id("type")).click();
    driver.findElement(By.id("type")).sendKeys("Sel ");
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("description")).sendKeys("Selenium type");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".buttons-pdf > span")).click();
    driver.findElement(By.cssSelector(".even:nth-child(6) > .select-checkbox")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.id("mat-input-1")).click();
    driver.findElement(By.id("mat-input-1")).sendKeys("Delete test");
    driver.findElement(By.cssSelector(".mat-button-wrapper > .text-white")).click();
    driver.findElement(By.linkText("Devices Models")).click();
    driver.findElement(By.linkText("Add Model")).click();
    driver.findElement(By.cssSelector(".ng-tns-c38-37 .mat-form-field-infix")).click();
    driver.findElement(By.cssSelector("#mat-option-0 > .mat-option-text")).click();
    driver.findElement(By.cssSelector(".mat-select-placeholder")).click();
    driver.findElement(By.cssSelector("#mat-option-3 > .mat-option-text")).click();
    driver.findElement(By.id("model")).click();
    driver.findElement(By.id("model")).sendKeys("Sel 220");
    driver.findElement(By.id("description")).click();
    driver.findElement(By.id("description")).sendKeys("Sel device");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector(".odd:nth-child(7) > .select-checkbox")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.id("mat-input-2")).click();
    driver.findElement(By.id("mat-input-2")).sendKeys("Deletion");
    driver.findElement(By.cssSelector(".mat-button-wrapper > .text-white")).click();
    driver.findElement(By.linkText("Business Units")).click();
    driver.findElement(By.linkText("Add Business Units")).click();
    driver.findElement(By.name("productName")).click();
    driver.findElement(By.name("productName")).sendKeys("Selenium seller");
    driver.findElement(By.name("description")).click();
    driver.findElement(By.name("description")).sendKeys("Selenium test");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.cssSelector(".odd:nth-child(7) > .select-checkbox")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.id("mat-input-3")).click();
    driver.findElement(By.id("mat-input-3")).sendKeys("Delete");
    driver.findElement(By.cssSelector(".mat-button-wrapper > .text-white")).click();
    driver.findElement(By.linkText("Currency")).click();
    driver.findElement(By.linkText("Add Currency")).click();
    driver.findElement(By.name("currencyName")).click();
    driver.findElement(By.name("currencyName")).sendKeys("Selenium");
    driver.findElement(By.name("currencyCode")).click();
    driver.findElement(By.name("currencyCode")).sendKeys("Sel");
    driver.findElement(By.name("numericValue")).click();
    driver.findElement(By.name("numericValue")).sendKeys("3");
    driver.findElement(By.name("numericValue")).click();
    driver.findElement(By.name("numericValue")).sendKeys("4");
    driver.findElement(By.name("numericValue")).click();
    driver.findElement(By.name("numericValue")).sendKeys("3");
    driver.findElement(By.name("numericValue")).click();
    driver.findElement(By.name("currencySymbol")).click();
    driver.findElement(By.name("currencySymbol")).sendKeys("SLC");
    driver.findElement(By.name("decimalValue")).click();
    driver.findElement(By.name("decimalValue")).sendKeys("1");
    driver.findElement(By.name("decimalValue")).click();
    driver.findElement(By.name("decimalValue")).sendKeys("2");
    driver.findElement(By.name("decimalValue")).click();
    driver.findElement(By.name("codeName")).click();
    driver.findElement(By.name("codeName")).sendKeys("Selnm");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".odd:nth-child(5) > .select-checkbox")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    driver.findElement(By.id("mat-input-8")).click();
    driver.findElement(By.id("mat-input-8")).sendKeys("Deletion");
    driver.findElement(By.cssSelector(".mat-button-wrapper > .text-white")).click();
    driver.findElement(By.cssSelector(".dropdown:nth-child(2) .fa-plus")).click();
    driver.findElement(By.cssSelector(".dropdown:nth-child(2) .fa-plus")).click();
    driver.findElement(By.cssSelector(".dropdown:nth-child(2) > .ng-star-inserted > .ng-star-inserted:nth-child(1) > .ng-star-inserted")).click();
    driver.findElement(By.cssSelector(".buttons-pdf > span")).click();
    driver.findElement(By.linkText("Password Complexity")).click();
  }
}
